### ISSUE TITLE
Improve `rootConnectionString` documentation

### ISSUE THREAD

**Issue by tadejstanic** [graphile/migrate#10]
I'd like to thank you for this interesting postgres db migration concept which is very promising.

While I was testing I've encountered several errors. When I run: 

```
npx graphile-migrate reset
```

I get `error: password authentication failed for user "x"`. User x doesn't exist in the database so the error is correct. But if I run `npx graphile-migrate watch` then the main database is updated. So it seems that not the same pg connection is used for the commands.

There is one error more that might be related to the previous one. If I execute:

```
npx graphile-migrate watch --shadow
```

a main database is updated not the shadow one.

I prepared testing [repo](https://github.com/tadejstanic/graphile-migrate-test) to reproduce those errors more easily.

**Comment by tadejstanic** [comment]
Everything was related to the default value for `rootConnectionString`, which is set to `template1`. I had to set this to the connection string which creates a connection to the database with superuser privileges.

**Comment by benjie** [comment]
I’m going to reopen this as a documentation issue. (If you fancy addressing it in the README please feel free 👍)

**Comment by tadejstanic** [comment]
Update applied in this PR #12.
