### ISSUE TITLE
Commits create empty SQL file

### ISSUE THREAD

**Issue by ncrmro** [graphile/migrate#101]
### Summary

When I attempt to commit a migration an empty SQL file is generated.

### Steps to reproduce

Check out [this repo](https://github.com/ncrmro/postgres-graphql) and run yarn commit the `ccurent.sql` file will be emptied and an new empty file `000001.sql` is created.

### Expected results

`000001.sql` containing the `current.sql`

### Actual results

An empty sql file.

### Additional context

Currently running inside of docker compose, whose directions can be found in the [README.md](https://github.com/ncrmro/postgres-graphql/blob/master/README.md)

**Comment by benjie** [comment]
Please try this outside of Docker and see if the issue persists.

**Comment by ncrmro** [comment]
@benjie it does appear to work fine outside of docker.

🤔🤔🤔

**Comment by ncrmro** [comment]
Even weirder is this works fine on Docker for Mac, but the original error was happening on my Linux workstation. 

Apologies for the false issue, thanks for the work your doing @benjie !

**Comment by shicholas** [comment]
Hi @ncrmro, we use Docker for graphile migrate and haven't experienced this problem. Maybe there's some issue with how you're mounting your native filesystem to docker? We use Docker-Compose for our development environments and have a separate container where we run commands like `yarn run graphile-migrate watch/commit`. You can check it out here if this helps. - https://github.com/NeonLaw/codebase/blob/development/docker-compose.yml#L120-L128
