### ISSUE TITLE
Feature: afterMigrate hook

### ISSUE THREAD

**Issue by frankdugan3** [graphile/migrate#13]
Similar to `afterReset`, I think a hook like `afterMigrations` would be super helpful. For example, in watch mode it could be used to re-run idempotent seed files, etc. each time migrations or `current.sql` are run.

**Comment by benjie** [comment]
I've added an `afterAllMigrations` hook in https://github.com/graphile/migrate/pull/15 but this won't run in watch mode (at least not currently) - it's intended for things like doing a DB schema dump.

Would `afterCurrent` (or some better name) be more appropriate for this use case? 

Now #15 is merged, adding new actions should be much more straight-forward.

**Comment by frankdugan3** [comment]
Sounds good to me!

**Comment by benjie** [comment]
This is out in `graphile-migrate@next` (v0.0.6)
