### ISSUE TITLE
Current released version?

### ISSUE THREAD

**Issue by jccr** [graphile/migrate#144]
### Summary

I see that the latest version is `1.2.0` on the npm registry, and there's a tag for it.
Is this the latest release? Is it stable?

### Additional context
I have looked at the GitHub releases page for this repo, hoping to to see if 1.2.0 was listed.
I have also seen what version the graphile/starter is using for further insight.

One reason I ask is that I'm looking to use the [`AllowInvalidHash`](https://github.com/graphile/migrate/pull/114) feature in production for my project.

**Comment by benjie** [comment]
Oops; 1.2.0 added to releases: https://github.com/graphile/migrate/releases/tag/v1.2.0
