### ISSUE TITLE
Show stderr/stdout instead of stacktrace in `watch` (and `commit`?)

### ISSUE THREAD

**Issue by tsnobip** [graphile/migrate#167]
### Feature description

`graphile-migrate watch` allows to run commands after running current migration, but when this command exits with a non-0 code, it just shows the stacktrace instead of stdout/stderr you're usually interested in.

Desired behavior:
<img width="668" alt="Capture d’écran 2022-10-20 à 12 04 03" src="https://user-images.githubusercontent.com/2479216/196919812-eeb0b069-ea97-41d5-aca3-26bf0eb79a55.png">

Current behavior:
<img width="655" alt="Capture d’écran 2022-10-20 à 11 21 47" src="https://user-images.githubusercontent.com/2479216/196919863-39e979c2-3dd8-457b-8470-fcc46dbfa765.png">

Same thing can somehow be said for `graphile-migrate commit`, right now it first shows the stacktrace before showing details, including stdout as an escaped string. it would likely be more readable to show stdout/stderr without processing.
<img width="688" alt="Capture d’écran 2022-10-20 à 12 05 17" src="https://user-images.githubusercontent.com/2479216/196920114-c3353ed3-b678-4830-8a34-e71319617d84.png">

### Motivating example

The most obvious example is when you want to run tests after current / migrations, you want the exit code to be taken in consideration for CI for example, but at the same time you want a readable output to understand which test failed.

The escape hatch I use for now is to ignore exit code when using `watch` but not in `commit`.

### Supporting development

I [tick all that apply]:

- [] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by zimme** [comment]
Probably related to #152.

**Comment by benjie** [comment]
Fix is out in 1.4.1

**Comment by zimme** [comment]
1.4.1 works for me 👍
