### ISSUE TITLE
Clarify Node.js versioning policy + supported versions

### ISSUE THREAD

**Issue by vosscodes** [graphile/migrate#172]
hi there!

per the [Node.js versioning policy](https://github.com/graphile/migrate#nodejs-versioning-policy), only LTS versions are supported - the current being node 12 and node 14.

> Once a Node.js version becomes "unsupported" (i.e. the maintenance LTS window ends), this project will no longer support it either. We may drop support for unmaintained versions of Node.js in a minor release.

are there any plans to officially support the current active/maintenance LTS versions? node 18 recently became the active LTS release and 16 has entered its maintenance window. node 12 LTS maintenance window ended 7 months ago, and 14 LTS will end maintenance in april.

**Comment by benjie** [comment]
I’m not aware of any compatibility issues with either of those; if you add them to CI (and it passes) and the README then they’re officially supported 👍
