### ISSUE TITLE
Improve docs and flow of uncommit

### ISSUE THREAD

**Issue by frankdugan3** [graphile/migrate#30]
The docs on uncommit explain _what_ it does, but not so much when it would be useful, especially given the warning. Perhaps that could be improved with something like:

> This is is useful, e.g, when committing to separate branches before merging into master. When such a conflict occurs, uncommitting can allow merging the separate changes, then committing them together.

Also, checking the commit hash to detect conflicts caused by using  uncommit and display a warning message with instructions on how to handle them would be really helpful:

>Your last ${n} commits have been changed upstream. Run graphile-migrate migrate --force to re-run all migrations since ${lastGoodMigration}.

**Comment by benjie** [comment]
Additional note: I think we should only allow `--force` to re-run the very latest commit. More than that should require a reset. So `${n}` shouldn't be needed.

**Comment by benjie** [comment]
I've addressed the docs but I've not made `migrate --force` deal with conflicts. Dealing with conflicts is a big topic and I don't want to add code to handle that right now. The temporary solution is to uncommit as many times as is necessary, and then to migrate.
