### ISSUE TITLE
[Feature Request] 'seed' or 'run' command

### ISSUE THREAD

**Issue by pixelpax** [graphile/migrate#37]
This isn't difficult to do as-is, but would be a great convenience command to just programmatically run an arbitrary sql file against the database.

My team likes to have a few different seed.sql files to test different situations with, and it'd be nice to be able to use graphile/migrate's settings and pgClient to do this for convenience and consistency. That way we could easily create quick one liners that can reset and seed the database in different ways for testing and development across environments. 

Something like the following to run arbitrary strings:

```typescript
export const runOnDb = async (
  sql: string,
  shadow: boolean,
  filename?: string,
) => {
  const parsedSettings = await parseSettings(getSettings(), shadow);
  withClient(
    parsedSettings.connectionString,
    parsedSettings,
    async (pgClient: PoolClient, context: Context) => {
      await runStringMigration(
        pgClient,
        parsedSettings,
        context,
        sql,
        filename || '',
      );
    },
  );
};
```

Would be low hanging fruit from existing commands.

**Comment by benjie** [comment]
`graphile-migrate run blah.sql` seems quite legit; doing all the parameter substitution, setting settings, etc. This seems a good idea.

**Comment by pixelpax** [comment]
Nice! Cool, I can take this but it might take a couple weeks for it to get to the front of my queue.

**Comment by benjie** [comment]
Sure; there’s no rush :)
