### ISSUE TITLE
Support Multiple Databases at Different Migration Versions?

### ISSUE THREAD

**Issue by markhalonen** [graphile/migrate#39]
I use your excellent postgraphile library and noticed this migration tool.

I have a use case where we have on-site databases that are not remotely accessible. So we anticipate doing on-site installs, leaving it for 6 months, and then returning and wanting to migrate the on-site database (and codebase) to our current product. So the on-site databases could be at any version.

Would this tool be a good solution for us? Or do you have recommendations for other tools?

Thanks!

**Comment by benjie** [comment]
`graphile-migrate` or any other migration system that keeps track of the migrations commited over time would be a good fit for this - they all store into the database what the "current version" is and then it runs all the committed migrations between that version and the latest version.

You might find that [migra](https://github.com/djrobstep/migra) is worth evaluating too; it works in a different way.
