### ISSUE TITLE
Command 'init' not understood

### ISSUE THREAD

**Issue by DanielFGray** [graphile/migrate#41]
some (most?) commands seem to throw 
```
Error: No .gmrc file found; please run `graphile-migrate init` first.
```

but when I run  `graphile-migrate init` it throws `Command 'init' not understood`

**Comment by benjie** [comment]
Yeah; I've not implemented that command yet: https://github.com/graphile/migrate#todo

You can see an example of a `.gmrc` file here:

https://github.com/graphile/starter/blob/master/@app/db/.gmrc

And docs on what the different parts are here:

https://github.com/graphile/migrate#configuration

**Comment by benjie** [comment]
Closing as duplicate of #29
