### ISSUE TITLE
Make migrationsFolder a setting

### ISSUE THREAD

**Issue by abeluck** [graphile/migrate#48]
When using the graphile-migrate API in a test suite, I would like to be able to change the migrations folder directory, ideally just by passing `migrationsFolder` in the settings object.

When I do that now I get an error:
```
The following config settings were not understood: 'migrationsFolder'
```

**Comment by benjie** [comment]
I'd consider a PR to do this; effectively you need to make this the fallback value: https://github.com/graphile/migrate/blob/8a9beda3531a25ec47a485260041daf70d431c11/src/settings.ts#L90
