### ISSUE TITLE
Expose uncommit command for library usage

### ISSUE THREAD

**Issue by PizzaPartyInc** [graphile/migrate#51]
Hey!

When you want to use graphile-migrate as a library, e.g `import * as gm from 'graphile-migrate;`, only 5 commands are exposed and `uncommit` is missing: 
[https://github.com/graphile/migrate/blob/master/src/commands/index.ts](https://github.com/graphile/migrate/blob/master/src/commands/index.ts)

It would be more convenient and consistent to expose it as well =)

**Comment by benjie** [comment]
Addressed in #52 (along with adding tests)
