### ISSUE TITLE
Failed to setup watch fixtures in Postgres database using graphile-migrate watch in 0.1.0

### ISSUE THREAD

**Issue by djmccormick** [graphile/migrate#69]
graphile-migrate: 0.1.0
postgres: 12-alpine (also tried 11-alpine with the same results)
node: 13.12.0

Environment variables:

	POSTGRES_DB=postgres
	POSTGRES_USER=postgres
	POSTGRES_HOST_AUTH_METHOD=trust
	
	DATABASE_URL=postgres://project_user@starter-postgres/project
	SHADOW_DATABASE_URL=postgres://project_user@starter-postgres/project_shadow
	ROOT_DATABASE_URL=postgres://postgres@starter-postgres/template1
	DEBUG=graphile-build-pg

Priming script:

	#!/bin/bash
	set -e

	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		create user project_user;
		create database project owner project_user;
		grant all privileges on database project to project_user;
		create database project_shadow owner project_user;
		grant all privileges on database project_shadow to project_user;
	EOSQL

After running the priming script, I confirmed that I had the users and databases available that I'd expect. Then, to confirm superuser status, I ran this same query with `postgres` and `project_user`:

	select usesuper from pg_user where usename = current_user;

For `postgres`, it returns `TRUE`. For `project_user` it returns `FALSE`.

When I try `graphile-migrate watch`, it seems to be generally working (current.sql runs and such), but I get the following error (which goes away if I give `DATABASE_USER` the `postgres` user instead of `project_user`):

	postgres | 2020-03-30 18:18:29.802 UTC [62] ERROR:  permission denied to create event trigger "postgraphile_watch_ddl"
	postgres | 2020-03-30 18:18:29.802 UTC [62] HINT:  Must be superuser to create an event trigger.
	postgres | 2020-03-30 18:18:29.802 UTC [62] STATEMENT:  begin; -- @see https://github.com/graphile/postgraphile/blob/886f8752f03d3fa05bdbdd97eeabb153a4d0343e/resources/watch-fixtures.sql
	postgres |
	postgres | -- Adds the functionality for PostGraphile to watch the database for schema
	postgres | -- changes. This script is idempotent, you can run it as many times as you
	postgres | -- would like.
	postgres |
	postgres | -- Drop the `postgraphile_watch` schema and all of its dependant objects
	postgres | -- including the event trigger function and the event trigger itself. We will
	postgres | -- recreate those objects in this script.
	postgres | drop schema if exists postgraphile_watch cascade;
	postgres |
	postgres | -- Create a schema for the PostGraphile watch functionality. This schema will
	postgres | -- hold things like trigger functions that are used to implement schema
	postgres | -- watching.
	postgres | create schema postgraphile_watch;
	postgres |
	postgres | create function postgraphile_watch.notify_watchers_ddl() returns event_trigger as $$
	postgres | begin
	postgres |   perform pg_notify(
	postgres |     'postgraphile_watch',
	postgres |     json_build_object(
	postgres |       'type',
	postgres |       'ddl',
	postgres |       'payload',
	postgres |       (select json_agg(json_build_object('schema', schema_name, 'command', command_tag)) from pg_event_trigger_ddl_commands() as x)
	postgres |     )::text
	postgres |   );
	postgres | end;
	postgres | $$ language plpgsql;
	postgres |
	postgres | create function postgraphile_watch.notify_watchers_drop() returns event_trigger as $$
	postgres | begin
	postgres |   perform pg_notify(
	postgres |     'postgraphile_watch',
	postgres |     json_build_object(
	postgres |       'type',
	postgres |       'drop',
	postgres |       'payload',
	postgres |       (select json_agg(distinct x.schema_name) from pg_event_trigger_dropped_objects() as x)
	postgres |     )::text
	postgres |   );
	postgres | end;
	postgres | $$ language plpgsql;
	postgres |
	postgres | -- Create an event trigger which will listen for the completion of all DDL
	postgres | -- events and report that they happened to PostGraphile. Events are selected by
	postgres | -- whether or not they modify the static definition of `pg_catalog` that
	postgres | -- `introspection-query.sql` queries.
	postgres | create event trigger postgraphile_watch_ddl
	postgres |   on ddl_command_end
	postgres |   when tag in (
	postgres |     -- Ref: https://www.postgresql.org/docs/10/static/event-trigger-matrix.html
	postgres |     'ALTER AGGREGATE',
	postgres |     'ALTER DOMAIN',
	postgres |     'ALTER EXTENSION',
	postgres |     'ALTER FOREIGN TABLE',
	postgres |     'ALTER FUNCTION',
	postgres |     'ALTER POLICY',
	postgres |     'ALTER SCHEMA',
	postgres |     'ALTER TABLE',
	postgres |     'ALTER TYPE',
	postgres |     'ALTER VIEW',
	postgres |     'COMMENT',
	postgres |     'CREATE AGGREGATE',
	postgres |     'CREATE DOMAIN',
	postgres |     'CREATE EXTENSION',
	postgres |     'CREATE FOREIGN TABLE',
	postgres |     'CREATE FUNCTION',
	postgres |     'CREATE INDEX',
	postgres |     'CREATE POLICY',
	postgres |     'CREATE RULE',
	postgres |     'CREATE SCHEMA',
	postgres |     'CREATE TABLE',
	postgres |     'CREATE TABLE AS',
	postgres |     'CREATE VIEW',
	postgres |     'DROP AGGREGATE',
	postgres |     'DROP DOMAIN',
	postgres |     'DROP EXTENSION',
	postgres |     'DROP FOREIGN TABLE',
	postgres |     'DROP FUNCTION',
	postgres |     'DROP INDEX',
	postgres |     'DROP OWNED',
	postgres |     'DROP POLICY',
	postgres |     'DROP RULE',
	postgres |     'DROP SCHEMA',
	postgres |     'DROP TABLE',
	postgres |     'DROP TYPE',
	postgres |     'DROP VIEW',
	postgres |     'GRANT',
	postgres |     'REVOKE',
	postgres |     'SELECT INTO'
	postgres |   )
	postgres |   execute procedure postgraphile_watch.notify_watchers_ddl();
	postgres |
	postgres | -- Create an event trigger which will listen for drop events because on drops
	postgres | -- the DDL method seems to get nothing returned from
	postgres | -- pg_event_trigger_ddl_commands()
	postgres | create event trigger postgraphile_watch_drop
	postgres |   on sql_drop
	postgres |   execute procedure postgraphile_watch.notify_watchers_drop();
	postgres | ;
	node | Failed to setup watch fixtures in Postgres database ️️⚠️
	node | This is likely because the PostgreSQL user in the connection string does not have sufficient privileges; you can solve this by passing the 'owner' connection string via '--owner-connection' / 'ownerConnectionString'. If the fixtures already exist, the watch functionality may still work.
	node | Enable DEBUG='graphile-build-pg' to see the error
	node | 2020-03-30T18:18:29.814Z graphile-build-pg error: permission denied to create event trigger "postgraphile_watch_ddl"
	node |     at Connection.parseE (/home/node/app/node_modules/pg/lib/connection.js:614:13)
	node |     at Connection.parseMessage (/home/node/app/node_modules/pg/lib/connection.js:413:19)
	node |     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:129:22)
	node |     at Socket.emit (events.js:315:20)
	node |     at addChunk (_stream_readable.js:297:12)
	node |     at readableAddChunk (_stream_readable.js:273:9)
	node |     at Socket.Readable.push (_stream_readable.js:214:10)
	node |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by djmccormick** [comment]
After using graphile-migrate more, I found that the other commands had similar issues and I wound up having to give the `postgres` user for all the connection strings in order to avoid issues with committing and migrating (and probably others). Perhaps I misunderstood the docs, but it seems like I have it set up as suggested in the README.

**Comment by benjie** [comment]
@djmccormick The error you list here seems to be coming from PostGraphile rather than graphile-migrate:

```
node | Failed to setup watch fixtures in Postgres database ️️⚠️
node | This is likely because the PostgreSQL user in the connection string does not have sufficient privileges; you can solve this by passing the 'owner' connection string via '--owner-connection' / 'ownerConnectionString'. If the fixtures already exist, the watch functionality may still work.
node | Enable DEBUG='graphile-build-pg' to see the error
node | 2020-03-30T18:18:29.814Z graphile-build-pg error: permission denied to create event trigger "postgraphile_watch_ddl"
n
```

The `ownerConnectionString` needs to be a superuser to install the watch fixtures. This is the only connection string that needs to be superuser, and you don't need to do this in production (since you probably don't use watch mode in production).

graphile-migrate is not intended to run commands from `current.sql` that require superuser privileges (e.g. `CREATE EXTENSION`) - those should be handled in hooks using the "root" user (a superuser, typically).

**Comment by RipTheJacker** [comment]
Ran into this issue as well. I feel like it would be better to have this kind of stuff more explicit as as install/init sql that can be run using `graphile-migrate run ...`, or referenced in the docs as such.
