### ISSUE TITLE
Release Request 0.2.0 (the one with "before" hooks)

### ISSUE THREAD

**Issue by Jakobo** [graphile/migrate#73]
With https://github.com/graphile/migrate/pull/70 merged into master, it would be great to cut a new release and expose the before hooks. Some common scenarios that the before hooks solve:

* **beforeReset** - Booting all clients connected to the database (or revoking their `CONNECT` permissions). Postgraphile already has reconnect logic, so this allows you to reset your mistakes in development and leave your stack running.
* **beforeAllMigrations** - Notify slack! Because while a lot of slack chatops usually are tracking releases, not all release systems announce db migrations.
* **beforeCurrent** - Take a snapshot. Super helpful when you're iterating on `current.sql` and know you're writing a data migration.

**Comment by benjie** [comment]
Released :+1:
